/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UqHTJ8QilBC
 */
import Link from "next/link"

export function video_return_response() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 lg:grid-cols-[1fr] lg:gap-12 xl:grid-cols-[1fr]">
          <div className="rounded-xl overflow-hidden">
            <span className="w-full aspect-video rounded-md bg-muted" />
          </div>
          <div className="py-2 grid gap-2 text-center">
            <h1 className="text-xl font-semibold line-clamp-2">New Video Title</h1>
            <div className="text-xs text-gray-500 dark:text-gray-400">A brief description about the video.</div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                download
                href="#"
              >
                Download Video
              </Link>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
                href="#"
              >
                Preview Video
              </Link>
            </div>
          </div>
          <div className="py-2 grid gap-2 text-center">
            <h1 className="text-xl font-semibold line-clamp-2">Video Thumbnail</h1>
            <img
              alt="Video Thumbnail"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </div>
    </section>
  )
}
